/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: n77bFagGCBm17CMGVYCTUy
import { createUseStyleTokens } from "@plasmicapp/react-web";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: n77bFagGCBm17CMGVYCTUy/projectModule
import projectcss from "./plasmic.module.css"; // plasmic-import: n77bFagGCBm17CMGVYCTUy/projectcss

const data = {
  base: `${projectcss.plasmic_tokens}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
