/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: n77bFagGCBm17CMGVYCTUy
import { createUseGlobalVariants } from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantszl7FOelMMksH } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: zl7fOelMMksH/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantszl7FOelMMksH
});
